# Generated by Django 3.2.8 on 2022-02-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220202_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
